### ISSUE TITLE
How to configuration on iOS 

### ISSUE THREAD

**Issue by carl-neng** [LeoJHarris/FilePicker#3]
Can you tell us details about configuration on developer account and project? Can guid us step by step. thank advance.

**Comment by LeoJHarris** [comment]
Have added in sample project with usages, will update the wiki page soon.

**Comment by LeoJHarris** [comment]
Hi have updated the wiki page. I suggest you follow something like this if struggling with iCloud setup on iOS: https://stackoverflow.com/questions/25938667/cloudkit-dashboard-says-i-have-no-icloud-containers-but-i-have-already-created
