### ISSUE TITLE
doc and xls

### ISSUE THREAD

**Issue by Nikdm46** [LeoJHarris/FilePicker#6]
Why i can only download pictures. Xls and Doc files are gray and I can not select them?

**Comment by Nikdm46** [comment]
var allowedUtis = new string[] {
                                                   UTType.UTF8PlainText,
                                                   UTType.PlainText,
                                                   UTType.RTF,
                                                   UTType.PNG,
                                                   UTType.Text,
                                                   UTType.PDF,
                                                   UTType.Image,
                                                   UTType.UTF16PlainText,
                                                   UTType.FileURL
                                               };
But audio video and xls doc docx its very important(((

**Comment by LeoJHarris** [comment]
This will be a simple change, will have a look at this week or the next for sure.

**Comment by Nikdm46** [comment]
That would be wonderful. Because I do not know how to recompile the plugin myself

**Comment by LeoJHarris** [comment]
Have added a new pre-release version 1.0.5-beta including the changes, I haven't thoroughly tested but have included the utils. Please download this version and if you can test and it works feel free to close this issue.

**Comment by ManojkumarKaliannan** [comment]
"Package LeoJHarris.Plugin.FilePicker 1.0.4 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package LeoJHarris.Plugin.FilePicker 1.0.4 supports:
  - monoandroid10 (MonoAndroid,Version=v1.0)
  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)"

Help me out ..Its not get installed in Xamarin ios (1.0.4)

**Comment by LeoJHarris** [comment]
@ManojkumarKaliannan if this is a separate issue to the above can you please open a new issue.

**Comment by Nikdm46** [comment]
Thank you, downloading documents works fine. It would be great if you add video formats in the same way - MOV Mp4 etc

**Comment by LeoJHarris** [comment]
@Nikdm46 sure i can add those, ill look at adding all applicable utils infact.

**Comment by Nikdm46** [comment]
Извините, вы добавили новые форматы? видео и т.д.
Новая версия не появилась?

**Comment by Nikdm46** [comment]
Sorry, have you added new formats? video etc.
The new version has not appeared?

**Comment by LeoJHarris** [comment]
Sorry I haven't yet. Just been busy, which formats are you wanting specifically?

**Comment by Nikdm46** [comment]
I think only video formats are most needed now. mp4 MOV etc.
To be honest, I do not know all the formats and how they need to be described that would be comfortable to take the video

**Comment by LeoJHarris** [comment]
Have added new version https://www.nuget.org/packages/LeoJHarris.Plugin.FilePicker/1.0.6-beta which includes those addtional utils, I have actually now added most applicable utils. and also bumped up the forms package. Its in beta so when searching nugetpackages enable include prerelease. When you happy with it that it works Ill move out of beta.

**Comment by LeoJHarris** [comment]
Regarding add Cyrillic support not sure yet..

**Comment by Nikdm46** [comment]
Do you happen to know what encoding is used? We need UTF-8 or something like that. if you can not change the encoding, I can probably translate the code if I know what encoding is used now

**Comment by LeoJHarris** [comment]
Yeah not too sure about the Cyrillic support, I can only suggest do a fork look into the code, try implement this and then do a PR and we can add this to the lib

**Comment by Nikdm46** [comment]
I just change the encoding on the server)) With the download of the video, there are also no problems. I think you can close the topic and release a new version
