### ISSUE TITLE
Package LeoJHarris.Plugin.FilePicker 1.0.4 is not compatible with xamarinios10 

### ISSUE THREAD

**Issue by ManojkumarKaliannan** [LeoJHarris/FilePicker#7]
"Package LeoJHarris.Plugin.FilePicker 1.0.4 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package LeoJHarris.Plugin.FilePicker 1.0.4 supports:

monoandroid10 (MonoAndroid,Version=v1.0)
portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
xamarinios10 (Xamarin.iOS,Version=v1.0)"
Help me out ..Its not get installed in Xamarin ios (1.0.4)

**Comment by ManojkumarKaliannan** [comment]
Package is not compatible with xamarinios10 when i tried to insert the nuget package in xamarin ios module

**Comment by ManojkumarKaliannan** [comment]
LeoJHarris.Plugin.FilePicker 1.0.4 is not compatible with xamarinios10

**Comment by LeoJHarris** [comment]
@ManojkumarKaliannan Well looking at what the message is telling you it does support xamarinios10:

"Package LeoJHarris.Plugin.FilePicker 1.0.4 is not compatible with xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86. Package LeoJHarris.Plugin.FilePicker 1.0.4 supports:

monoandroid10 (MonoAndroid,Version=v1.0)
portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
 **xamarinios10 (Xamarin.iOS,Version=v1.0)"**

Your trying to install into a project that targets: xamarinios10 (Xamarin.iOS,Version=v1.0) / win-x86

Notice the win-x86, this could be causing you issues for the target project.

**Comment by LeoJHarris** [comment]
I would suggest creating a blank new project for XForms with iOS and try installing it from nuget and if it doesnt work let me know, if you see win-x86 again in doing this check how you are creating your XForms project.
